version: '3.7'

volumes:
  cb_node_api_data:
  cb_node_mongo_data:
  cb_node_redis:
    driver: local

services:
  cb_node_api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8001"
    container_name: cb_node_api
    links:
      - cb_node_mongo
    volumes:
      - .:/usr/src/app
  cb_node_mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: cb_node_mongo
    volumes:
      - cb_node_mongo_data:/data/db
  cb_node_redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    container_name: cb_node_redis
    command: redis-server --save 20 1 --loglevel warning --requirepass fuaGUCIVUI678597yHUIHbiivu97668
    volumes: 
      - cb_node_redis:/data